"""initial schema

Revision ID: c28151f088bb
Revises: 
Create Date: 2026-09-04 07:30:54.723205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c28151f088bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AIModelConfig',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.Enum('google', 'openrouter', 'groq', 'openai', 'anthropic', 'deepseek', 'custom', 'github', name='provider'), nullable=False),
    sa.Column('modelId', sa.String(), nullable=False),
    sa.Column('displayName', sa.String(), nullable=False),
    sa.Column('contextWindow', sa.String(), nullable=False),
    sa.Column('latency', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modelId')
    )
    op.create_table('User',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('passwordHash', sa.String(), nullable=False),
    sa.Column('displayName', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('CopilotConversation',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('userId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('projectId', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Project',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ownerId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sourceType', sa.Enum('ZIP', 'GITHUB', 'PASTE', name='sourcetype'), nullable=False),
    sa.Column('status', sa.Enum('READY', 'ANALYZING', 'FAILED', 'ARCHIVED', name='projectstatus'), nullable=False),
    sa.Column('repositoryUrl', sa.String(), nullable=True),
    sa.Column('defaultBranch', sa.String(), nullable=True),
    sa.Column('currentCommit', sa.String(), nullable=True),
    sa.Column('sourcePath', sa.String(), nullable=True),
    sa.Column('workspacePath', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('framework', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ownerId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ProviderCredential',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('userId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.Enum('google', 'openrouter', 'groq', 'openai', 'anthropic', 'deepseek', 'custom', 'github', name='provider'), nullable=False),
    sa.Column('encryptedKey', sa.String(), nullable=False),
    sa.Column('baseUrl', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'provider')
    )
    op.create_table('UserSetting',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('userId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('primaryProvider', sa.Enum('google', 'openrouter', 'groq', 'openai', 'anthropic', 'deepseek', 'custom', 'github', name='provider'), nullable=False),
    sa.Column('primaryModel', sa.String(), nullable=False),
    sa.Column('autoRunTests', sa.Boolean(), nullable=False),
    sa.Column('minimumConfidence', sa.Integer(), nullable=False),
    sa.Column('sandboxGuardrails', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('AnalysisRun',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('projectId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='analysisstatus'), nullable=False),
    sa.Column('requestedBy', sa.String(), nullable=False),
    sa.Column('startedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('errorMessage', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('AnalyticsEvent',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('projectId', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analyticsevent_user_name_created', 'AnalyticsEvent', ['userId', 'name', 'createdAt'], unique=False)
    op.create_table('ContextDocument',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('projectId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('storagePath', sa.String(), nullable=False),
    sa.Column('sizeBytes', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('contentText', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('indexedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CopilotMessage',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('conversationId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('modelUsed', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversationId'], ['CopilotConversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GitOperation',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('projectId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('commit', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ProjectSetting',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('projectId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('autoRunTests', sa.Boolean(), nullable=False),
    sa.Column('minimumConfidence', sa.Integer(), nullable=False),
    sa.Column('sandboxGuardrails', sa.Boolean(), nullable=False),
    sa.Column('maxCpu', sa.Float(), nullable=False),
    sa.Column('maxMemory', sa.String(), nullable=False),
    sa.Column('timeoutSeconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projectId')
    )
    op.create_table('Workspace',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('projectId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rootPath', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projectId')
    )
    op.create_table('Bug',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('projectId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('analysisRunId', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('severity', sa.Enum('Critical', 'High', 'Medium', 'Low', name='severity'), nullable=False),
    sa.Column('status', sa.Enum('Open', 'InReview', 'Fixed', 'Closed', 'AISuggested', 'ApplyingFix', name='bugstatus'), nullable=False),
    sa.Column('aiStatus', sa.Enum('Pending', 'Ready', 'Applied', name='aistatus'), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('component', sa.String(), nullable=False),
    sa.Column('filePath', sa.String(), nullable=True),
    sa.Column('lineNumber', sa.Integer(), nullable=True),
    sa.Column('stackTrace', sa.String(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('loggedDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysisRunId'], ['AnalysisRun.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projectId', 'code')
    )
    op.create_index('ix_bug_project_status_severity', 'Bug', ['projectId', 'status', 'severity'], unique=False)
    op.create_table('CodeChangeProposal',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('conversationId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('messageId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('file', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('startLine', sa.Integer(), nullable=False),
    sa.Column('endLine', sa.Integer(), nullable=False),
    sa.Column('originalCode', sa.String(), nullable=False),
    sa.Column('proposedCode', sa.String(), nullable=False),
    sa.Column('diffSummary', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PERMISSION', 'APPROVED_AND_APPLIED', 'REJECTED', 'REVERTED', name='proposalstatus'), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversationId'], ['CopilotConversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['messageId'], ['CopilotMessage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('messageId')
    )
    op.create_table('ContextChunk',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('documentId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['documentId'], ['ContextDocument.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documentId', 'ordinal')
    )
    op.create_table('ErrorRecord',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('projectId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('analysisRunId', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('stackTrace', sa.String(), nullable=True),
    sa.Column('filePath', sa.String(), nullable=True),
    sa.Column('lineNumber', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysisRunId'], ['AnalysisRun.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_errorrecord_project_fingerprint', 'ErrorRecord', ['projectId', 'fingerprint'], unique=False)
    op.create_table('PipelinePhase',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('analysisRunId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'RUNNING', 'PENDING', 'FAILED', name='phasestatus'), nullable=False),
    sa.Column('durationMs', sa.Integer(), nullable=True),
    sa.Column('validationStatus', sa.Enum('IDLE', 'RUNNING', 'PASSED', 'FAILED', 'RE_ANALYZING', name='validationstatus'), nullable=False),
    sa.Column('validationReport', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('subprocesses', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('startedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysisRunId'], ['AnalysisRun.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysisRunId', 'number')
    )
    op.create_table('TestRun',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('projectId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('analysisRunId', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('durationMs', sa.Integer(), nullable=False),
    sa.Column('stdout', sa.String(), nullable=True),
    sa.Column('stderr', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysisRunId'], ['AnalysisRun.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BugOccurrence',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('bugId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('errorId', sa.String(), nullable=True),
    sa.Column('lineNumber', sa.Integer(), nullable=True),
    sa.Column('filePath', sa.String(), nullable=True),
    sa.Column('observedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bugId'], ['Bug.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FixProposal',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('bugId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('projectId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('analysisRunId', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('provider', sa.Enum('google', 'openrouter', 'groq', 'openai', 'anthropic', 'deepseek', 'custom', 'github', name='provider'), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('patchSummary', sa.String(), nullable=False),
    sa.Column('unifiedDiff', sa.String(), nullable=False),
    sa.Column('originalCode', sa.String(), nullable=True),
    sa.Column('proposedCode', sa.String(), nullable=True),
    sa.Column('affectedFiles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('linesChanged', sa.Integer(), nullable=False),
    sa.Column('estimatedMinutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Ready', 'Applied', 'Superseded', name='fixstatus'), nullable=False),
    sa.Column('validationStatus', sa.Enum('IDLE', 'RUNNING', 'PASSED', 'FAILED', 'RE_ANALYZING', name='validationstatus'), nullable=False),
    sa.Column('validationReport', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('appliedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysisRunId'], ['AnalysisRun.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bugId'], ['Bug.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PipelineLog',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('analysisRunId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('phaseId', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['analysisRunId'], ['AnalysisRun.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phaseId'], ['PipelinePhase.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipelinelog_run_timestamp', 'PipelineLog', ['analysisRunId', 'timestamp'], unique=False)
    op.create_table('FixValidation',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('fixId', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'RUNNING', 'PASSED', 'FAILED', 'RE_ANALYZING', name='validationstatus'), nullable=False),
    sa.Column('testPassRate', sa.String(), nullable=False),
    sa.Column('totalTests', sa.Integer(), nullable=False),
    sa.Column('passedTests', sa.Integer(), nullable=False),
    sa.Column('failedTests', sa.Integer(), nullable=False),
    sa.Column('regressionFound', sa.Boolean(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('diffSnippet', sa.String(), nullable=True),
    sa.Column('cycleCount', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fixId'], ['FixProposal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FixValidation')
    op.drop_index('ix_pipelinelog_run_timestamp', table_name='PipelineLog')
    op.drop_table('PipelineLog')
    op.drop_table('FixProposal')
    op.drop_table('BugOccurrence')
    op.drop_table('TestRun')
    op.drop_table('PipelinePhase')
    op.drop_index('ix_errorrecord_project_fingerprint', table_name='ErrorRecord')
    op.drop_table('ErrorRecord')
    op.drop_table('ContextChunk')
    op.drop_table('CodeChangeProposal')
    op.drop_index('ix_bug_project_status_severity', table_name='Bug')
    op.drop_table('Bug')
    op.drop_table('Workspace')
    op.drop_table('ProjectSetting')
    op.drop_table('GitOperation')
    op.drop_table('CopilotMessage')
    op.drop_table('ContextDocument')
    op.drop_index('ix_analyticsevent_user_name_created', table_name='AnalyticsEvent')
    op.drop_table('AnalyticsEvent')
    op.drop_table('AnalysisRun')
    op.drop_table('UserSetting')
    op.drop_table('ProviderCredential')
    op.drop_table('Project')
    op.drop_table('CopilotConversation')
    op.drop_table('User')
    op.drop_table('AIModelConfig')
    # ### end Alembic commands ###
